package net.homeip.jtjang.MileageRunAppEngine;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CityInfo {
	@SuppressWarnings("serial")
	public static final Map<String, String> AllCities =
			new HashMap<String, String>() {
		{
			put("New York","LGA");
			put("Los Angeles","LAX");
			put("Chicago","ORD");
			put("Houston","IAH");
			put("Philadelphia","TTN");
			put("Phoenix","PHX");
			put("San Diego","SAN");
			put("San Antonio","SAT");
			put("Dallas","DFW");
			put("Detroit","DTW");
			put("San Jose","SJC");
			put("Indianapolis","IND");
			put("Jacksonville","OAJ");
			put("San Francisco","SFO");
			put("Columbus","CMH");
			put("Austin","AUS");
			put("Memphis","MEM");
			put("Baltimore","BWI");
			put("Milwaukee","MKE");
			put("Charlotte","CLT");
			put("El Paso","ELP");
			put("Boston","BOS");
			put("Seattle"," SEA");
			put("Washington"," IAD");
			put("Denver","QWM");
			put("Nashville","BNA");
			put("Portland","PDX");
			put("Oklahoma City","OKC");
			put("Las Vegas","LAS");
			put("Tucson","TUS");
			put("Long Beach","LGB");
			put("Albuquerque","ABQ");
			put("New Orleans","MSY");
			put("Cleveland","CLE");
			put("Fresno","FAT");
			put("Sacramento","SMF");
			put("Kansas City","MCI");
			put("Atlanta","ATL");
			put("Omaha","OMA");
			put("Oakland","OAK");
			put("Tulsa","TUL");
			put("Miami","MPB");
			put("Minneapolis","MSP");
			put("Colorado Springs","COS");
			put("Wichita","ICT");
			put("Santa Ana","SNA");
			put("Pittsburgh","PIT");
			put("Tampa","TPA");
			put("Cincinnati","CVG");
			put("Toledo","TOL");
			put("Buffalo","BUF");
			put("Corpus Christi","CRP");
			put("Newark","EWR");
			put("Stockton","SCK");
			put("Bakersfield","BFL");
			put("Anchorage","ANC");
			put("Louisville","SDF");
			put("Norfolk","ORF");
			put("Birmingham","BHM");
			put("Lincoln","LNK");
			put("Greensboro","GSO");
			put("Baton Rouge","BTR");
			put("Fort Wayne","FWA");
			put("Madison","MSN");
			put("Rochester","ROC");
			put("Modesto","MOD");
			put("Lubbock","LBB");
			put("Montgomery","MGM");
			put("Orlando","MCO");
			put("Durham","RDU");
			put("Shreveport","SHV");
			put("Laredo","LRD");
			put("Spokane","GEG");
			put("Des Moines","DSM");
			put("Grand Rapids","GPZ");
			put("Richmond","RIC");
			put("Reno","RNO");
			put("Boise","BOI");
			put("Columbus","CMH");
			put("Little Rock","LIT");
			put("Newport News","PHF");
			put("Jackson","MKL");
			put("Amarillo","AMA");
			put("Providence","PVD");
			put("Worcester","ORH");
			put("Knoxville","TYS");
			put("Ontario","ONT");
			put("Huntsville","HSV");
			put("Fort Lauderdale","FLL");
			put("Dayton","DAY");
			put("Brownsville","BRO");
			put("Chattanooga","CHA");
			put("Tallahassee","TLH");
			put("Santa Rosa","STS");
			put("Springfield","SGF");
			put("Rockford","RFD");
			put("Springfield","SGF");
			put("Hampton","PHF");
			put("Syracuse","SYR");
			put("Salem","SLE");
			put("Eugene","EUG");
			put("Sioux Falls","FSD");
			put("Alexandria","AEX");
			put("Peoria","PIA");
			put("Savannah","SAV");
			put("Lancaster","LNS");
			put("Concord","CCR");
			put("New Haven","HVN");
			put("Hartford","BDL");
			put("Fayetteville","FAY");
			put("Cedar Rapids","CID");
			put("Topeka","FOE");
			put("Flint","FNT");
			put("Lansing","LAN");
			put("Evansville","EVV");
			put("Columbia","CAE");
			put("Waco","ACT");
		}
	};

	@SuppressWarnings("serial")
	public static final Map<String, Integer> BigCities = 
			new HashMap<String, Integer>() {
		{
			int i=118;
			put("New York",--i);
			put("Los Angeles",--i);
			put("Chicago",--i);
			put("Houston",--i);
			put("Philadelphia",--i);
			put("Phoenix",--i);
			put("San Diego",--i);
			put("San Antonio",--i);
			put("Dallas",--i);
			put("Detroit",--i);
			put("San Jose",--i);
			put("Indianapolis",--i);
			put("Jacksonville",--i);
			put("San Francisco",--i);
			put("Columbus",--i);
			put("Austin",--i);
			put("Memphis",--i);
			put("Baltimore",--i);
			put("Milwaukee",--i);
			put("Charlotte",--i);
			put("El Paso",--i);
			put("Boston",--i);
			put("Seattle",--i);
			put("Washington",--i);
			put("Denver",--i);
			put("Nashville",--i);
			put("Portland",--i);
			put("Oklahoma City",--i);
			put("Las Vegas",--i);
			put("Tucson",--i);
			put("Long Beach",--i);
			put("Albuquerque",--i);
			put("New Orleans",--i);
			put("Cleveland",--i);
			put("Fresno",--i);
			put("Sacramento",--i);
			put("Kansas City",--i);
			put("Atlanta",--i);
			put("Omaha",--i);
			put("Oakland",--i);
			put("Tulsa",--i);
			put("Miami",--i);
			put("Minneapolis",--i);
			put("Colorado Springs",--i);
			put("Wichita",--i);
			put("Santa Ana",--i);
			put("Pittsburgh",--i);
			put("Tampa",--i);
			put("Cincinnati",--i);
			put("Toledo",--i);
			put("Buffalo",--i);
			put("Corpus Christi",--i);
			put("Newark",--i);
			put("Stockton",--i);
			put("Bakersfield",--i);
			put("Anchorage",--i);
			put("Louisville",--i);
			put("Norfolk",--i);
			put("Birmingham",--i);
			put("Lincoln",--i);
			put("Greensboro",--i);
			put("Baton Rouge",--i);
			put("Fort Wayne",--i);
			put("Madison",--i);
			put("Rochester",--i);
			put("Modesto",--i);
			put("Lubbock",--i);
			put("Montgomery",--i);
			put("Orlando",--i);
			put("Durham",--i);
			put("Shreveport",--i);
			put("Laredo",--i);
			put("Spokane",--i);
			put("Des Moines",--i);
			put("Grand Rapids",--i);
			put("Richmond",--i);
			put("Reno",--i);
			put("Boise",--i);
			put("Columbus",--i);
			put("Little Rock",--i);
			put("Newport News",--i);
			put("Jackson",--i);
			put("Amarillo",--i);
			put("Providence",--i);
			put("Worcester",--i);
			put("Knoxville",--i);
			put("Ontario",--i);
			put("Huntsville",--i);
			put("Fort Lauderdale",--i);
			put("Dayton",--i);
			put("Brownsville",--i);
			put("Chattanooga",--i);
			put("Tallahassee",--i);
			put("Santa Rosa",--i);
			put("Springfield",--i);
			put("Rockford",--i);
			put("Springfield",--i);
			put("Hampton",--i);
			put("Syracuse",--i);
			put("Salem",--i);
			put("Eugene",--i);
			put("Sioux Falls",--i);
			put("Alexandria",--i);
			put("Peoria",--i);
			put("Savannah",--i);
			put("Lancaster",--i);
			put("Concord",--i);
			put("New Haven",--i);
			put("Hartford",--i);
			put("Fayetteville",--i);
			put("Cedar Rapids",--i);
			put("Topeka",--i);
			put("Flint",--i);
			put("Lansing",--i);
			put("Evansville",--i);
			put("Columbia",--i);
			put("Waco",--i);
		}
	};

	@SuppressWarnings("serial")
	public static final List<String> Top10Cities =
			new ArrayList<String>() {
		{
			add("New York");
			add("Los Angeles");
			add("Chicago");
			add("Houston");
			add("Philadelphia");
			add("Phoenix");
			add("San Diego");
			add("San Antonio");
			add("Dallas");
			add("Detroit");
		}
	};

}
